### ISSUE TITLE
Which target names should be standardized?

### ISSUE THREAD

**Issue by ezzatron** [make-files/makefiles#1]
Thought I'd get the ball rolling. I can think of a few target names we probably need to come up with:

- Installing dependencies
- Testing
- Test code coverage
- Opening test coverage reports
- Pre-commit checks
- Pre-publishing
- Running the app/server
- Building for release
- Building for debugging

Agreeing on some standard project "types", and what each target means in each context would probably useful too. I'm thinking along the lines of library vs. app, compiled vs. not (maybe even app vs. server?)

**Comment by jmalloc** [comment]
> (maybe even app vs. server?)

Do you mean web-app in this context?

**Comment by ezzatron** [comment]
> Do you mean web-app in this context?

Maybe? But also potentially more of a long running server vs. command line tool type split. Not sure if there would actually be a meaningful difference in Makefiles for those.

**Comment by jmalloc** [comment]
Yeah, I see. From the perspective of Go, at least, I see no need to make a distinction there.

I think the naming we have been using so far is still *largely* OK, some quick notes/questions on each below:

- **Installing dependencies** - `vendor` or `deps`, advise against `install` as in the *nix world this typlically means "install the built app onto the system"
- **Testing** - I see no reason to change from `test` 
- **Test code coverage** - I see no reason to change from `coverage` 
- **Opening test coverage reports** - I have taken to using `coverage-open`, just as its easier for autocompletion imo (vs `open-coverage`).
- **Pre-commit checks** - IIRC this is the one where we use `prepare` but this already has some meaning to NPM or Node more generally?
- **Pre-publishing** - Meaning pruning dev dependencies etc?
- **Running the app/server** - It's reasonably common IME to have multiple binaries in a single repo, so there's not necessarily "an app". I typically define a `run` target in the project-specific `Makefile`, rather than attempting to do this generically.  We can probably do better.
- **Building for release** - `release` - as per C++/compiled language world
- **Building for debugging** - `debug` - as per C++/compiled language world

**Comment by ezzatron** [comment]
Cool, I agree with all of that.

> * **Pre-commit checks** - IIRC this is the one where we use `prepare` but this already has some meaning to NPM or Node more generally?

Yes, NPM and Yarn support `prepare` as a script type. It has to do with "preparing" a package for publishing to the NPM registry. In most cases that means transpiling.

> * **Pre-publishing** - Meaning pruning dev dependencies etc?

More like transpiling before publishing to the NPM registry, similar to what `prepare` means in the JS world (https://docs.npmjs.com/misc/scripts#prepublish-and-prepare).

> * **Running the app/server** - It's reasonably common IME to have multiple binaries in a single repo, so there's not necessarily "an app". I typically define a `run` target in the project-specific `Makefile`, rather than attempting to do this generically.  We can probably do better.

That's fair. In the case of "servers" I'm not sure if a distinction needs to be made between:
- Running a server that "hosts" the current project as an application (i.e. the case of a project that uses something like webpack-dev-server)
- Running the current project, which *is* a server itself
